"""fixed_first_migration

Revision ID: 56d24019aede
Revises: 
Create Date: 2024-04-27 21:17:21.092777

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56d24019aede'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('spec_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('reg', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('drive', sa.String(), nullable=True),
    sa.Column('seats', sa.String(), nullable=True),
    sa.Column('doors', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('reg_number', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bargain_price', sa.Integer(), nullable=True),
    sa.Column('export_price', sa.Integer(), nullable=True),
    sa.Column('vat', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_info_body_type'), 'car_info', ['body_type'], unique=False)
    op.create_index(op.f('ix_car_info_color'), 'car_info', ['color'], unique=False)
    op.create_index(op.f('ix_car_info_doors'), 'car_info', ['doors'], unique=False)
    op.create_index(op.f('ix_car_info_drive'), 'car_info', ['drive'], unique=False)
    op.create_index(op.f('ix_car_info_fuel'), 'car_info', ['fuel'], unique=False)
    op.create_index(op.f('ix_car_info_make'), 'car_info', ['make'], unique=False)
    op.create_index(op.f('ix_car_info_model'), 'car_info', ['model'], unique=False)
    op.create_index(op.f('ix_car_info_seats'), 'car_info', ['seats'], unique=False)
    op.create_index(op.f('ix_car_info_transmission'), 'car_info', ['transmission'], unique=False)
    op.create_index(op.f('ix_car_info_type'), 'car_info', ['type'], unique=False)
    op.create_index(op.f('ix_car_info_vat'), 'car_info', ['vat'], unique=False)
    op.create_table('car_makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_makes_code'), 'car_makes', ['code'], unique=True)
    op.create_index(op.f('ix_car_makes_make_name'), 'car_makes', ['make_name'], unique=False)
    op.create_table('car_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_types_code'), 'car_types', ['code'], unique=True)
    op.create_index(op.f('ix_car_types_type_name'), 'car_types', ['type_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_types_type_name'), table_name='car_types')
    op.drop_index(op.f('ix_car_types_code'), table_name='car_types')
    op.drop_table('car_types')
    op.drop_index(op.f('ix_car_makes_make_name'), table_name='car_makes')
    op.drop_index(op.f('ix_car_makes_code'), table_name='car_makes')
    op.drop_table('car_makes')
    op.drop_index(op.f('ix_car_info_vat'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_type'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_transmission'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_seats'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_model'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_make'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_fuel'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_drive'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_doors'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_color'), table_name='car_info')
    op.drop_index(op.f('ix_car_info_body_type'), table_name='car_info')
    op.drop_table('car_info')
    # ### end Alembic commands ###
